// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210125174410_yearExperiencePrograminLanguage")]
    partial class yearExperiencePrograminLanguage
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("API.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("AppUser");
                });

            modelBuilder.Entity("API.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Language");
                });

            modelBuilder.Entity("API.Entities.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Buisness")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BusinessValidation")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Create")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("FreelanceValidation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SalaryId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TermsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Buisness");

                    b.HasIndex("SalaryId");

                    b.HasIndex("TermsId");

                    b.ToTable("Offre");
                });

            modelBuilder.Entity("API.Entities.OfferLanguages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Favoris")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OffreId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("OffreId");

                    b.ToTable("OffreLanguagesSpeak");
                });

            modelBuilder.Entity("API.Entities.OfferProgramingLanguages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Favoris")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OffreId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProgramingLanguageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("YearExperience")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OffreId");

                    b.HasIndex("ProgramingLanguageId");

                    b.ToTable("OffreLanguagesComputer");
                });

            modelBuilder.Entity("API.Entities.Penalty", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TauxHorraireId")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("TauxHorraireId");

                    b.ToTable("Penalty");
                });

            modelBuilder.Entity("API.Entities.ProgramingLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProgramingLanguage");
                });

            modelBuilder.Entity("API.Entities.Salary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalAmount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Salary");
                });

            modelBuilder.Entity("API.Entities.TauxHorraire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeTaux")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Valeur")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TimeLimit");
                });

            modelBuilder.Entity("API.Entities.Terms", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Begin")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Time")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Time");

                    b.ToTable("Terms");
                });

            modelBuilder.Entity("API.Entities.Time", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeTime")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Valeur")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Time");
                });

            modelBuilder.Entity("API.Entities.Business", b =>
                {
                    b.HasBaseType("API.Entities.AppUser");

                    b.Property<string>("Activity")
                        .HasColumnType("TEXT");

                    b.Property<string>("LegalStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameBusiness")
                        .HasColumnType("TEXT");

                    b.Property<string>("Siret")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Business");
                });

            modelBuilder.Entity("API.Entities.Freelance", b =>
                {
                    b.HasBaseType("API.Entities.AppUser");

                    b.Property<int>("Ago")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Freelance");
                });

            modelBuilder.Entity("API.Entities.Offer", b =>
                {
                    b.HasOne("API.Entities.Business", "Creator")
                        .WithMany()
                        .HasForeignKey("Buisness");

                    b.HasOne("API.Entities.Salary", "Salary")
                        .WithMany()
                        .HasForeignKey("SalaryId");

                    b.HasOne("API.Entities.Terms", "Terms")
                        .WithMany()
                        .HasForeignKey("TermsId");

                    b.Navigation("Creator");

                    b.Navigation("Salary");

                    b.Navigation("Terms");
                });

            modelBuilder.Entity("API.Entities.OfferLanguages", b =>
                {
                    b.HasOne("API.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId");

                    b.HasOne("API.Entities.Offer", "Offre")
                        .WithMany()
                        .HasForeignKey("OffreId");

                    b.Navigation("Language");

                    b.Navigation("Offre");
                });

            modelBuilder.Entity("API.Entities.OfferProgramingLanguages", b =>
                {
                    b.HasOne("API.Entities.Offer", "Offre")
                        .WithMany()
                        .HasForeignKey("OffreId");

                    b.HasOne("API.Entities.ProgramingLanguage", "ProgramingLanguage")
                        .WithMany()
                        .HasForeignKey("ProgramingLanguageId");

                    b.Navigation("Offre");

                    b.Navigation("ProgramingLanguage");
                });

            modelBuilder.Entity("API.Entities.Penalty", b =>
                {
                    b.HasOne("API.Entities.TauxHorraire", "TauxHorraire")
                        .WithMany()
                        .HasForeignKey("TauxHorraireId");

                    b.Navigation("TauxHorraire");
                });

            modelBuilder.Entity("API.Entities.Terms", b =>
                {
                    b.HasOne("API.Entities.Time", "End")
                        .WithMany()
                        .HasForeignKey("Time");

                    b.Navigation("End");
                });
#pragma warning restore 612, 618
        }
    }
}
